export const FETCH_ACCOUNTS = 'fetchAccounts'
export const FETCHING_ACCOUNTS = 'fetchingAccounts'
export const FETCH_TRANSACTIONS = 'fetchTransactions'
export const FETCHING_TRANSACTIONS = 'fetchingTransactions'
export const FETCH_MEME = 'fetchMeme'
export const FETCHING_MEME = 'fetchingMeme'